spring:
  profiles:
    default: local
  application:
    name: eureka-server

server:
  port: 8443
  ssl:
    key-store: "classpath:ssl/keystore.jks"
    key-store-password: "password"

app:
  password-file-path: "/secrets/password.txt"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/